export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Problem } from './Problem'
export { default as Solution } from './Solution'
export { default as HowItWorks } from './HowItWorks'
export { default as SocialProof } from './SocialProof'
export { default as Footer } from './Footer'
